project_id = "aziiemouzibnmlmkvzsf"

[functions.generate-questions]
verify_jwt = false

[functions.chat-with-ai]
verify_jwt = false

[functions.send-discord-message]
verify_jwt = false

[functions.generate-follow-up-tasks]
verify_jwt = false

[functions.generate-lecture]
verify_jwt = false
